### ISSUE TITLE
Learn how to write file names

### ISSUE THREAD

**Issue by C0deDaedalus** [vivekjha2310/notepadforfun#1]
### Give Some meaningful name to your files instead of useless names
 **1.html**       OR      **thhfgh.txt**      are too lame for a name.
### Give unique names to file instead of common names
 **file.js        OR       **website.txt**     are common names. *BE SPECIFIC* to names.
### Give fullname to files where too common
 **theme.jpg**     ---------------->    **theme_mytheme.jpg**  OR **theme_blacktheme.jpg**
### Always write file extensions where possible
 **changable theme**  --------->   **theme_changeable.<extension>**

**Comment by vivekjha2310** [comment]
ohkkk
